services:
  functions:
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    restart: always
    networks:
      my_custom_network:
        ipv4_address: ${APP_IP}

networks:
  my_custom_network:
    external: true
